theme: jekyll-theme-dinky

title: PDF Qurik
description: A small utility to generate PDFs from images or scans in an easy and fast way.

github:
  zip_url: https://github.com/dragotin/pdfquirk/archive/master.zip
  repository_name: pdfquirk
  is_project_page: true
  owner_url: https://github.com/dragotin
  
